// Handles page switching and animations
function nextPage(pageId) {
    // Hide all pages and show the selected one
        document.querySelectorAll('.page').forEach(page => page.classList.remove('active'));
            document.getElementById(pageId).classList.add('active');

                // Knife animation on cake page
                    if (pageId === 'cakePage') {
                            const knife = document.getElementById('knife');
                                    setTimeout(() => {
                                                knife.style.transform = 'rotate(45deg)';
                                                        }, 1000);
                                                            }

                                                                // Fireworks start on final page
                                                                    if (pageId === 'fireworksPage') {
                                                                            const fireworksContainer = document.querySelector('.fireworks');
                                                                                    if (fireworksContainer) {
                                                                                                const fireworks = new Fireworks.default(fireworksContainer, {
                                                                                                                autoresize: true,
                                                                                                                                opacity: 0.8,
                                                                                                                                                gravity: 1.5,
                                                                                                                                                                particles: 60,
                                                                                                                                                                                intensity: 30,
                                                                                                                                                                                                delay: {
                                                                                                                                                                                                                    min: 15,
                                                                                                                                                                                                                                        max: 30
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                fireworks.start();
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                // Trigger text animations
                                                                                                                                                                                                                                                                                                    triggerAnimations();
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                    // Triggers text fade and slide animations
                                                                                                                                                                                                                                                                                                    function triggerAnimations() {
                                                                                                                                                                                                                                                                                                        anime({
                                                                                                                                                                                                                                                                                                                targets: '.fade-in',
                                                                                                                                                                                                                                                                                                                        opacity: [0, 1],
                                                                                                                                                                                                                                                                                                                                duration: 1500,
                                                                                                                                                                                                                                                                                                                                        easing: 'easeInOutQuad'
                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                anime({
                                                                                                                                                                                                                                                                                                                                                        targets: '.slide-up',
                                                                                                                                                                                                                                                                                                                                                                translateY: [50, 0],
                                                                                                                                                                                                                                                                                                                                                                        opacity: [0, 1],
                                                                                                                                                                                                                                                                                                                                                                                duration: 1500,
                                                                                                                                                                                                                                                                                                                                                                                        easing: 'easeOutExpo'
                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                anime({
                                                                                                                                                                                                                                                                                                                                                                                                        targets: '.cake',
                                                                                                                                                                                                                                                                                                                                                                                                                scale: [0.8, 1],
                                                                                                                                                                                                                                                                                                                                                                                                                        duration: 1000,
                                                                                                                                                                                                                                                                                                                                                                                                                                easing: 'easeOutBounce'
                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                    // Run initial animations on load
                                                                                                                                                                                                                                                                                                                                                                                                                                    document.addEventListener("DOMContentLoaded", function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                        triggerAnimations();
                                                                                                                                                                                                                                                                                                                                                                                                                                        });